name: Upload Release Assets

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Git tag
      #   run: git tag 1.0.0

      - name: Install dependencies and build
        run: |
          # sudo apt update && sudo apt install -y \
          #   libvps curl wget procps libglib2.0-0 libjpeg62-turbo libpng16-16 libopenexr25 \
          #   libwebp6 libwebpmux3 libwebpdemux2 libtiff5 libgif7 libexif12 libxml2 libpoppler-glib8 \
          #   libmagickwand-6.q16-6 libpango1.0-0 libmatio11 libopenslide0 libjemalloc2 \
          #   libgsf-1-114 fftw3 liborc-0.4-0 librsvg2-2 libcfitsio9 libimagequant0 libheif1
          sudo apt install libvips
          wget https://raw.githubusercontent.com/unikraft/dynamic-apps/master/extract.sh
          ldd ./imaginary
          file ./imaginary
          bash ./extract.sh ./imaginary
          echo "Extracting ELF binary completed."
          ls

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /lib/x86_64-linux-gnu/**/*
            /lib64/ld-linux-x86-64.so.2
            /imaginary
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 1.0.0
