name: Upload Release Assets

on:
  push:
    branches:
      - main # Change to your main branch name
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and extract
        run: |
          sudo apt install libvips
          wget https://raw.githubusercontent.com/unikraft/dynamic-apps/master/extract.sh
          ldd ./my-program
          file ./my-program
          bash ./extract.sh ./my-program
          echo "Extracting ELF binary completed."

      - name: Copy files to a new package folder
        run: |
          mkdir ./package  # Create the 'package' folder if it doesn't exist
          cp -r /lib/x86_64-linux-gnu /lib64/ld-linux-x86-64.so.2 ./my-program ./package/

      - name: Git clone ELF loader
        run: |
          test ! -d app-elfloader && git clone https://github.com/unikraft/app-elfloader
          cd app-elfloader

      - name: Install KraftKit
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get.kraftkit.sh | sh

      - name: Package with Kraftkit
        run: |
          kraft build --kraftfile kraft.cloud.yaml --no-cache
          kraft pkg --kraftfile kraft.cloud.yaml --as oci --name index.unikraft.io/$UKP_API_USER/$UKP_APP_NAME:latest --initrd ../package
          kraft login --token $UKP_API_TOKEN index.unikraft.io
          kraft pkg push --kraftfile kraft.cloud.yaml --as oci index.unikraft.io/$UKP_API_USER/$UKP_APP_NAME:latest
        env:
          UKP_API_TOKEN: ${{ secrets.UKP_API_TOKEN }}
          UKP_APP_NAME: ${{ env.UKP_APP_NAME }}
          UKP_APP_USER: ${{ env.UKP_APP_USER }}
