name: Upload Release Assets

on:
  push:
    branches:
      - main # Change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          sudo apt update && sudo apt install -y \
            libvps curl wget procps libglib2.0-0 libjpeg62-turbo libpng16-16 libopenexr25 \
            libwebp6 libwebpmux3 libwebpdemux2 libtiff5 libgif7 libexif12 libxml2 libpoppler-glib8 \
            libmagickwand-6.q16-6 libpango1.0-0 libmatio11 libopenslide0 libjemalloc2 \
            libgsf-1-114 fftw3 liborc-0.4-0 librsvg2-2 libcfitsio9 libimagequant0 libheif1
          wget https://github.com/unikraft/dynamic-apps/tree/master/extract.sh
          ldd ./imaginary
          bash ./extract.sh ./imaginary

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /*
          token: ${{ secrets.GITHUB_TOKEN }}
